using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEditor.PackageManager;
using UnityEditor.PackageManager.Requests;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace ChessFight.Editor
{
    [InitializeOnLoad]
    public static class NetworkSetup
    {
        const string Package = "com.rlabrecque.steamworks.net";
        const string Url = "https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net#c21a8f0e31c56ae8707130967faf491f7dd7c0d8";
        static AddRequest request;
        static double started;
        static bool Installed => UnityEditor.PackageManager.PackageInfo.GetAllRegisteredPackages().Any(p => p.name == Package);
        static NetworkSetup() { EditorApplication.delayCall += AutoInstall; }
        static void AutoInstall()
        {
            if (Installed || Application.isBatchMode || SessionState.GetBool("ChessFight.SteamInstallAttempted", false)) return;
            Install();
        }
        [MenuItem("ChessFight/Network/Install Steamworks dependency")]
        public static void Install()
        {
            if (request != null || Installed) return;
            SessionState.SetBool("ChessFight.SteamInstallAttempted", true);
            Debug.Log("[ChessFight] Installing Steamworks.NET 2025.164.1 using Unity Package Manager...");
            request = Client.Add(Url); started = EditorApplication.timeSinceStartup;
            EditorApplication.update += Poll;
        }
        static void Poll()
        {
            if (request == null) return;
            if (!request.IsCompleted && EditorApplication.timeSinceStartup - started < 180) return;
            EditorApplication.update -= Poll;
            if (request.IsCompleted && request.Status == StatusCode.Success)
                Debug.Log("[ChessFight] Steamworks installed. Open SampleScene and press Play. Commit Packages/manifest.json and packages-lock.json generated by UPM.");
            else Debug.LogError("[ChessFight] Steamworks installation failed: " + (request.Error?.message ?? "Timed out") + ". Install Git for Windows, restart Unity Hub, then use ChessFight > Network > Install Steamworks dependency.");
            request = null;
        }
        [MenuItem("ChessFight/Network/Open test scene")]
        public static void OpenScene()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            EditorSceneManager.OpenScene("Assets/Scenes/SampleScene.unity");
        }
        [MenuItem("ChessFight/Network/Build Windows development test")]
        public static void Build()
        {
            if (!Installed) throw new InvalidOperationException("Install Steamworks first from ChessFight > Network.");
            const string path = "Builds/NetworkTest/ChessFight.exe";
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            var report = BuildPipeline.BuildPlayer(new BuildPlayerOptions
            {
                scenes = new[] { "Assets/Scenes/SampleScene.unity" }, locationPathName = path,
                target = BuildTarget.StandaloneWindows64, options = BuildOptions.Development
            });
            if (report.summary.result != BuildResult.Succeeded) throw new InvalidOperationException("Network test build failed.");
            File.Copy("steam_appid.txt", "Builds/NetworkTest/steam_appid.txt", true);
            Debug.Log("[ChessFight] Development build: " + Path.GetFullPath(path));
        }
    }
}
